#!/bin/bash
if [ -z $1 ] || [ $1 = 'system-audio' ]
then
	echo "Error: an output file should be specified"
	exit 1
fi
if [ $2 = 'system-audio' ]
then
	AUDIO_INPUT=`pactl list sources short | grep monitor | awk '{print $2}'`
	AUDIO_CHANNEL=`pactl list sources short | grep monitor | awk '{print $5}' | egrep -o '[0-9]+'`
	AUDIO_RATE=`pactl list sources short | grep monitor | awk '{print $6}' | egrep -o '[0-9]+'`
	AUDIO_SYSTEM="-f pulse -ac $AUDIO_CHANNEL -ar $AUDIO_RATE -i $AUDIO_INPUT"
else
	AUDIO_SYSTEM=''
fi
echo "Setting a rectangle to record"
echo "Position the mouse cursor on the left-top corner (enter to continue)"
read
eval "$(xdotool getmouselocation -shell 2>/dev/null)"
LEFT_TOP_X=$X
LEFT_TOP_Y=$Y
echo "Position the mouse cursor on the right-bottom corner (enter to continue)"
read
eval "$(xdotool getmouselocation -shell 2>/dev/null)"
RIGHT_BOTTOM_X=$X
RIGHT_BOTTOM_Y=$Y
if ! [[ $LEFT_TOP_X -lt $RIGHT_BOTTOM_X && $LEFT_TOP_Y -lt $RIGHT_BOTTOM_Y ]]
then
	echo "Error: invalid positions given. Left-top (${LEFT_TOP_X},${LEFT_TOP_Y}) should be less then right-bottom (${RIGHT_BOTTOM_X},${RIGHT_BOTTOM_Y})"
	exit 1
fi
WIDTH=`expr $RIGHT_BOTTOM_X - $LEFT_TOP_X`
HEIGHT=`expr $RIGHT_BOTTOM_Y - $LEFT_TOP_Y`
for i in {5..1}; do
	echo $i
	sleep 1s
done
echo GO!
ffmpeg $AUDIO_SYSTEM -f x11grab -s ${WIDTH}x${HEIGHT} -framerate 30 -i :0+${LEFT_TOP_X},${LEFT_TOP_Y} -vcodec libx264 -preset ultrafast -qp 0 -pix_fmt yuv444p $1 
