#!/bin/bash

setup(){
	INTERVAL_IN_SECONDS=`expr 2 \* 86400` # Download every 2 days
	QUERIES=(wallpaper amazing funny awesome wonderful space)
	AMOUNT=10
	OUT_DIR=/home/estevao/Pictures/favorite-wallpapers

	LOGS_DIR=`dirname "$0"`/.logs/wallpapers
	CHECKPOINT_FILE=$LOGS_DIR/checkpoint
	SAVED_WALLPAPERS_FILE=$LOGS_DIR/saved_wallpapers

	[[ $1 = force ]] && IS_TO_FORCE_DOWNLOAD=true || IS_TO_FORCE_DOWNLOAD=false
	if [[ ! -d $LOGS_DIR || ! -f $CHECKPOINT_FILE || ! -f $SAVED_WALLPAPERS_FILE ]]; then
		mkdir -p $LOGS_DIR
		echo "0" > $CHECKPOINT_FILE && : > $SAVED_WALLPAPERS_FILE
		IS_TO_FORCE_DOWNLOAD=true
	fi
	PREVIOUS_TIMESTAMP=`cat $CHECKPOINT_FILE`
	CURRENT_TIMESTAMP=`date +%s`
}

is_to_download_now(){
	CURRENT=$1
	PREVIOUS=$2
	[[ $PREVIOUS -gt $CURRENT ]] && echo "ERROR: previous time is greater than current: $PREVIOUS > $CURRENT" >&2 && exit 1

	if [[ `expr $CURRENT - $PREVIOUS` -lt $INTERVAL_IN_SECONDS ]]; then
		return 1 # do not download
	fi
	return 0 # do download
}

download_wallpapers(){
	echo "INFO: Begin download..."
	TEMP_OUT_DIR=$OUT_DIR/.tmp-$CURRENT_TIMESTAMP
	mkdir -p $TEMP_OUT_DIR
	# TODOs:
	# download images to temporary location at $TEMP_OUT_DIR
	# store name of downloaded files to some file (so that we can get them back later)
	# return 0 if it's successful; otherwise, return 1.
	echo "INFO: All done"
}

commit_downloads(){
	# Before moving downloaded files from source to dest, it removes previously donwloaded files
	# so that we can have the behavior of cyclic wallpapers, and avoid conflicting file names
	SOURCE_DIR=$1
	DEST_DIR=$2
	PREVIOUS_FILES=${@:3}
	[[ ! -d $SOURCE_DIR || ! -d $DEST_DIR ]] && echo "ERROR: Directories not found: $SOURCE_DIR, $DEST_DIR" >&2 && exit 1
	
	for FILE in $PREVIOUS_FILES; do
		rm -f $SOURCE_DIR/$FILE
	done
	mv $SOURCE_DIR/* $DEST_DIR
}

verify_dependencies(){
	[[ `which randimg` == "" ]] && echo "ERROR: Needs to install randimg, see how at ttps://github.com/estevaog3/randimg" >&2 && exit 1
}

verify_dependencies
setup $*
if [[ $IS_TO_FORCE_DOWNLOAD = false ]]; then 
	is_to_download_now $CURRENT_TIMESTAMP $PREVIOUS_TIMESTAMP
	[[ $? = 1 ]] && echo "INFO: it's not the time to download. Nothing done." && exit 0
fi
download_wallpapers
commit_downloads $TEMP_OUT_DIR $OUT_DIR #TODO: pass in previously downloaded images here
